export const tireFilterableFields = [
  "searchTerm",
  "name",
  "loadRange",
  "tireType",
  "category",
  "brand",
  "make",
  "model",
  "year",
  "trim",
  "tireSize",
  "drivingType",
  "width",
  "ratio",
  "diameter",
  "vehicleType",
  "price",
  "stockQuantity",
  "constructionType",
  "sectionWidth",
  "rimDiameter",
  "loadIndex",
  "loadIndexRange",
];

export const tireSearchableFields = [
  "name",
  "description",
  "loadRange",
  "tireType",
  "constructionType",
  "category",
  "productLine",
  "treadPattern",
];
